spring.application.name=CentralizedHealthCard

## Active Profile ##
spring.profiles.active=dev

## Database Configuration ##
#spring.datasource.url=jdbc:mysql://localhost:3306/CHC
#spring.datasource.username=root
#spring.datasource.password=root

## JPA ##
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false

## Custom Port No. ##
server.port=8081

## Actuator ##
management.endpoints.web.exposure.include=*

## JWT Configuration ##
jwt.secret=YourSuperSecretKeyThatIsAtLeast64BytesLongForHMACSHA512AlgorithmSecurityPurpose2026!
