spring.application.name=CentralizedHealthCard

## PostgreSQL Database ##
spring.datasource.url=jdbc:postgresql://localhost:5432/chc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

## JPA ##
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

## Custom Port No. ##
server.port=8081

## Actuator ##
management.endpoints.web.exposure.include=*

## JWT Configuration ##
jwt.secret=YourSuperSecretKeyThatIsAtLeast64BytesLongForHMACSHA512AlgorithmSecurityPurpose2026!
