spring.application.name=CentralizedHealthCard

## Active Profile ##
spring.profiles.active=dev

## Database Configuration ##
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8v5c2egvqtc73br76u0-a.singapore-postgres.render.com:5432/chc_db?sslmode=require}
spring.datasource.username=chc_db_user
spring.datasource.password=jKKbtcFOqYKFAcAL2vbp6OwdMQOxSXxa

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## JPA ##
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false

## Custom Port No. ##
server.port=8081

## Actuator ##
management.endpoints.web.exposure.include=*

## JWT Configuration ##
jwt.secret=YourSuperSecretKeyThatIsAtLeast64BytesLongForHMACSHA512AlgorithmSecurityPurpose2026!

## SPRING AI (Using Gemini via OpenAI compatibility) ##
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key=${GEMINI_API_KEY:temp-key-placeholder}
spring.ai.openai.chat.options.model=gemini-1.5-flash
spring.ai.openai.chat.options.temperature=0.3
